### ISSUE TITLE
r200 calculation (and potentially other values) don't update after changing zlens

### ISSUE THREAD

**Issue by kevinea42** [qminor/qlens-beta#11]
After changing zlens, certain things should change, such as r200 for an nfw halo, but don't. See the attached example session.
[r200 issue session.txt](https://github.com/qminor/qlens-beta/files/2106746/r200.issue.session.txt)

**Comment by qminor** [comment]
This has been fixed now. The redshift of a lens can be changed using "lens update". Now, zlens only gives the default redshift of a lens that gets created; each lens can have its own redshift, hoewever, which is shown in the list of lenses when you type "lens".
