### ISSUE TITLE
Parameter names don't include derived parameter

### ISSUE THREAD

**Issue by kevinea42** [qminor/qlens-beta#12]
I created a derived parameter with this:
`fit dparams add kappa_r 20`

However, the resulting '.paramnames' and '.latex_paramnames' files don't include the new derived parameter. As a result, mkdist throws an error:
`Error: not all parameter names are given in file './Abell_611_v21.cNFW.kappa_d.spo.paramnames'`

**Comment by qminor** [comment]
Hi Kevin,

I am not getting this error when I add derived parameters like this. Can you send me the script and data file you're using?

Thanks,
Quinn

**Comment by kevinea42** [comment]
Sure, here you are. I looked at the output chain file and it has 14 columns, implying 12 parameters since the first and last columns aren’t parameters. I’ve included the .paramnames file, which you can see has 11 names in it.
Best,
Kevin







On Jul 5, 2018, at 8:06 PM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Kevin,

I am not getting this error when I add derived parameters like this. Can you send me the script and data file you're using?

Thanks,
Quinn

**Comment by qminor** [comment]
Hi Kevin,

I'm not getting the attachments (I seem to recall GitHub doesn't do
attachments). Can you send it to my gmail?

Thanks,
Quinn

**Comment by qminor** [comment]
Ok, this issue has been fixed. The problem was with "fit save_bestfit", which overwrote the file produced by the nested sampling and wasn't saving the derived parameter names. Now the derived parameter names are in there.
