### ISSUE TITLE
Compilation Error: wchar.h

### ISSUE THREAD

**Issue by kevinea42** [qminor/qlens-beta#6]
When trying to compile the most recent update of qlens-beta, I got this error:

`Kevins-MBP:qlens-beta kevin$ make
mpicxx -DUSE_MPI -w -fopenmp -O3  -DUSE_OPENMP        -c qlens.cpp
In file included from /usr/local/include/c++/7.1.0/bits/postypes.h:40:0,
                 from /usr/local/include/c++/7.1.0/iosfwd:40,
                 from /usr/local/include/c++/7.1.0/ios:38,
                 from /usr/local/include/c++/7.1.0/ostream:38,
                 from /usr/local/include/c++/7.1.0/iostream:39,
                 from vector.h:6,
                 from sort.h:5,
                 from qlens.h:4,
                 from qlens.cpp:4:
/usr/local/include/c++/7.1.0/cwchar:44:10: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
          ^~~~~~~~~
compilation terminated.
make: *** [qlens.o] Error 1`

Please advise as to how to remedy. Thanks.

**Comment by qminor** [comment]
Hi Kevin,

Try doing a "make clean" followed by "make". Sometimes the makefile doesn't
always remake certain files that need to be remade (because I may not have
listed every dependency in the makefile). Let me know if that fixes it.

Quinn

**Comment by qminor** [comment]
Hi Kevin,

Here's an idea. Let's revert to a previous qlens version and see if the
problem persists. To do this, type 'git log'. It will show all the upgrades
you've done--they're listed as "commits". Pick an upgrade prior to when
this problem occured (say, from a few days ago), and copy the commit id# to
your clipboard. Then, type the following: "git reset --hard #" where # is
the number of the commit you're reverting to. This should do it. Now, do a
"make clean" followed by "make". Is the problem still there? Let me know.

After you're finished with this experiment, you can just do a "git pull" to
revert to the latest version.

Quinn

**Comment by qminor** [comment]
Closing this issue since it was resolved on your end.

Thanks,
Quinn

**Comment by kevinea42** [comment]
Of course. In the future, do you want me to close things like this? Do I have that ability?

On Dec 5, 2017, at 2:30 PM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #6<https://github.com/qminor/qlens-beta/issues/6>.
